/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Taxi B&B GmbH API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all bookings
 */
export const ListBookingsResponseItem = zod.object({
  "id": zod.number(),
  "pickupLocation": zod.string(),
  "destination": zod.string(),
  "customerName": zod.string(),
  "customerLastName": zod.string(),
  "customerPhone": zod.string(),
  "scheduledTime": zod.string().nullish(),
  "estimatedDistance": zod.number().nullish(),
  "estimatedDuration": zod.number().nullish(),
  "passengerCount": zod.number().nullish(),
  "notes": zod.string().nullish(),
  "foundVia": zod.string().nullish(),
  "laterPickup": zod.string().nullish(),
  "returnPickupTime": zod.string().nullish(),
  "returnPickupLocation": zod.string().nullish(),
  "returnDestination": zod.string().nullish(),
  "callbackTime": zod.string().nullish(),
  "status": zod.enum(['new', 'accepted', 'completed', 'rejected']),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListBookingsResponse = zod.array(ListBookingsResponseItem)


/**
 * @summary Create a booking request
 */
export const CreateBookingBody = zod.object({
  "pickupLocation": zod.string(),
  "destination": zod.string(),
  "customerName": zod.string(),
  "customerLastName": zod.string(),
  "customerPhone": zod.string(),
  "scheduledTime": zod.string().nullish(),
  "estimatedDistance": zod.number().nullish(),
  "estimatedDuration": zod.number().nullish(),
  "passengerCount": zod.number().nullish(),
  "notes": zod.string().nullish(),
  "foundVia": zod.string().nullish(),
  "laterPickup": zod.string().nullish(),
  "returnPickupTime": zod.string().nullish(),
  "returnPickupLocation": zod.string().nullish(),
  "returnDestination": zod.string().nullish(),
  "callbackTime": zod.string().nullish()
})


/**
 * @summary Get a booking by ID
 */
export const GetBookingParams = zod.object({
  "id": zod.coerce.number()
})

export const GetBookingResponse = zod.object({
  "id": zod.number(),
  "pickupLocation": zod.string(),
  "destination": zod.string(),
  "customerName": zod.string(),
  "customerLastName": zod.string(),
  "customerPhone": zod.string(),
  "scheduledTime": zod.string().nullish(),
  "estimatedDistance": zod.number().nullish(),
  "estimatedDuration": zod.number().nullish(),
  "passengerCount": zod.number().nullish(),
  "notes": zod.string().nullish(),
  "foundVia": zod.string().nullish(),
  "laterPickup": zod.string().nullish(),
  "returnPickupTime": zod.string().nullish(),
  "returnPickupLocation": zod.string().nullish(),
  "returnDestination": zod.string().nullish(),
  "callbackTime": zod.string().nullish(),
  "status": zod.enum(['new', 'accepted', 'completed', 'rejected']),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Update booking status
 */
export const UpdateBookingStatusParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateBookingStatusBody = zod.object({
  "status": zod.enum(['new', 'accepted', 'completed', 'rejected'])
})

export const UpdateBookingStatusResponse = zod.object({
  "id": zod.number(),
  "pickupLocation": zod.string(),
  "destination": zod.string(),
  "customerName": zod.string(),
  "customerLastName": zod.string(),
  "customerPhone": zod.string(),
  "scheduledTime": zod.string().nullish(),
  "estimatedDistance": zod.number().nullish(),
  "estimatedDuration": zod.number().nullish(),
  "passengerCount": zod.number().nullish(),
  "notes": zod.string().nullish(),
  "foundVia": zod.string().nullish(),
  "laterPickup": zod.string().nullish(),
  "returnPickupTime": zod.string().nullish(),
  "returnPickupLocation": zod.string().nullish(),
  "returnDestination": zod.string().nullish(),
  "callbackTime": zod.string().nullish(),
  "status": zod.enum(['new', 'accepted', 'completed', 'rejected']),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


